# Uncomment this line to define a global platform for your project
platform :ios, '6.0'

target 'FMDBDemo' do
pod 'FMDB', '~> 2.5'
pod 'FMDBWithRuntime', '~> 1.0.0'
end

target 'FMDBDemoTests' do

end

